spring.application.name=clientcrud
spring.profiles.active=test
spring.jpa.open-in-view=true

server.port=8000

spring.datasource.url=jdbc:h2:mem:clients
spring.datasource.username=test
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true